<?php
/**
 * @file
 * Drupal needs this blank file.
 */

function t17n_menu() {
  $items['admin/structure/t17n'] = array(
    'title'             => 'Taxonomy effects',
    'description'       => 'Administer vocabularies with t17n',
    'page callback'     => 't17n_voc_list',
    'access arguments'  => array('administer taxonomy'),
    'file'              => 't17n.admin.inc',
  );

  $items['admin/structure/t17n/voc/%taxonomy_vocabulary_machine_name'] = array(
    'title callback' => 'taxonomy_admin_vocabulary_title_callback',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('t17n_settings_voc_form', 4),
    'access arguments' => array('administer taxonomy'),
    'file' => 't17n.admin.inc',
  );

  return $items;
}